# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  vulkan_test_config = debug

else ifeq ($(config),release)
  vulkan_test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := vulkan-test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

vulkan-test:
ifneq (,$(vulkan_test_config))
	@echo "==== Building vulkan-test ($(vulkan_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f vulkan-test.make config=$(vulkan_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f vulkan-test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   vulkan-test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"